"""update pk

Revision ID: 4d4438dff313
Revises: ab7de8e58341
Create Date: 2023-01-07 02:40:08.533626

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4d4438dff313"
down_revision = "ab7de8e58341"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
